version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  producer:
    build:
      context: ./Producer
    depends_on:
      - kafka
    command: ["python", "Kafka_Producer.py"]

  consumer_Flag:
    build:
      context: ./Flag_Consumer
    depends_on:
      - kafka
      - redis
    command: ["python", "Kafka_Consumer_Flagging.py"]

  consumer2:
    build:
      context: ./Retrain_Consumer
    depends_on:
      - kafka
      - redis
    command: ["python", "Kafka_Consumer_Retraining.py"]

  flask_backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: ["python", "dashboard_backend.py"]

  streamlit_frontend:
    build:
      context: ./Frontend
    ports:
      - "8501:8501"
    depends_on:
      - flask_backend
    command: ["streamlit", "run", "Frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
